name: Feature Request
description: Suggest a new feature or enhancement for the Replane JavaScript SDK
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Other approaches you've thought about.
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Related Package
      description: Which package does this feature relate to?
      options:
        - "@replanejs/sdk"
        - "@replanejs/react"
        - "@replanejs/next"
        - "@replanejs/svelte"
        - New package
        - All packages
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area of the SDK does this feature relate to?
      options:
        - Core Client
        - SSE / Real-time Updates
        - React Hooks
        - React Context
        - Next.js SSR/SSG
        - Svelte Stores
        - Override Evaluation
        - TypeScript Types
        - Error Handling
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or code examples about the feature request here.
    validations:
      required: false

